/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "ConsenSys Tessera",
  "tagline": "An open-source private transaction manager developed under the Apache 2.0 license and written in Java. Tessera serves as a privact manager for privacy-enabled Ethereum clients like GoQuorum and Hyperledger Besu",
  "url": "https://consensys.github.io",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "throw",
  "favicon": "img/favicon.ico",
  "trailingSlash": false,
  "organizationName": "ConsenSys",
  "projectName": "doc.tessera",
  "deploymentBranch": "gh-pages",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/home/jfernandes/workspace/docs/doc.tessera/sidebars.js",
          "editUrl": "https://github.com/ConsenSys/doc.tessera/tree/main/",
          "routeBasePath": "/docs",
          "remarkPlugins": [
            null
          ],
          "include": [
            "**/*.md",
            "**/*.mdx"
          ],
          "exclude": [
            "**/_*.{js,jsx,ts,tsx,md,mdx}",
            "**/_*/**",
            "**/*.test.{js,jsx,ts,tsx}",
            "**/__tests__/**"
          ],
          "showLastUpdateAuthor": true,
          "showLastUpdateTime": true,
          "includeCurrentVersion": true
        },
        "theme": {
          "customCss": "/home/jfernandes/workspace/docs/doc.tessera/src/css/custom.css"
        }
      }
    ],
    [
      "redocusaurus",
      {
        "specs": [
          {
            "id": "using-remote-url",
            "spec": "https://raw.githubusercontent.com/rohit-gohri/redocusaurus/main/website/openapi/single-file/openapi.yaml",
            "route": "/api/"
          }
        ],
        "theme": {
          "primaryColor": "#3655d5",
          "primaryColorDark": "#a2aeec",
          "options": {
            "disableSearch": true
          },
          "theme": {}
        }
      }
    ]
  ],
  "themeConfig": {
    "algolia": {
      "appId": "NSRFPEJ4NC",
      "apiKey": "cea41b975ad6c9a01408dfda6e0061d3",
      "indexName": "tessera",
      "contextualSearch": true,
      "externalUrlRegex": "external\\.com|domain\\.com",
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 5
    },
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": true
      },
      "versionPersistence": "localStorage"
    },
    "navbar": {
      "title": "Tessera",
      "logo": {
        "alt": "tessera",
        "src": "img/logo.svg",
        "srcDark": "img/logo_dark.svg",
        "width": 32,
        "height": 32
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "docSidebar",
          "docId": "index",
          "position": "left",
          "label": "Docs"
        },
        {
          "href": "https://github.com/ConsenSys/tessera",
          "className": "header-github-link",
          "position": "right"
        },
        {
          "href": "https://discord.com/channels/697535391594446898/905421497416433704",
          "className": "header-discord-link",
          "position": "right"
        },
        {
          "href": "https://twitter.com/consensys",
          "className": "header-twitter-link",
          "position": "right"
        },
        {
          "href": "https://hub.docker.com/r/quorumengineering/tessera",
          "className": "header-dockerhub-link",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Learn",
          "items": [
            {
              "label": "How To",
              "to": "/docs/category/how-to"
            },
            {
              "label": "Concepts",
              "to": "/docs/category/concepts"
            },
            {
              "label": "Tutorials",
              "to": "/docs/category/tutorials"
            },
            {
              "label": "Reference",
              "to": "/docs/category/reference"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Discord",
              "href": "https://discord.com/channels/697535391594446898/725135157652226060"
            },
            {
              "label": "Issues",
              "href": "https://github.com/ConsenSys/tessera/issues"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "Documentation on GitHub",
              "href": "https://github.com/ConsenSys/doc.tessera"
            },
            {
              "label": "ConsenSys",
              "href": "https://consensys.net"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2023 ConsenSys, Inc. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "languageTabs": [
      {
        "highlight": "bash",
        "language": "curl",
        "logoClass": "bash"
      },
      {
        "highlight": "python",
        "language": "python",
        "logoClass": "python"
      },
      {
        "highlight": "go",
        "language": "go",
        "logoClass": "go"
      },
      {
        "highlight": "javascript",
        "language": "nodejs",
        "logoClass": "nodejs"
      }
    ],
    "metadata": []
  },
  "plugins": [
    [
      "@docusaurus/plugin-google-gtag",
      {
        "trackingID": "G-",
        "anonymizeIP": true
      }
    ],
    [
      "@docusaurus/plugin-google-tag-manager",
      {
        "containerId": "GTM-"
      }
    ]
  ],
  "themes": [],
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
